# Generated by Django 4.1.7 on 2023-04-15 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+', max_length=15)),
                ('mail', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'About Me',
                'verbose_name_plural': 'About Me',
            },
        ),
        migrations.CreateModel(
            name='AboutUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('succesed_students', models.IntegerField(blank=True, default=100, null=True)),
                ('new_students', models.IntegerField(blank=True, default=1, null=True)),
                ('current_teachers', models.BigIntegerField(blank=True, null=True)),
                ('awards', models.IntegerField(blank=True, null=True)),
                ('video', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'About University',
                'verbose_name_plural': 'About University',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Meeting Category',
                'verbose_name_plural': 'Meeting Categories',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='course/')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='meeting/')),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_title', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('video', models.FileField(upload_to='video/')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Navbar',
                'verbose_name_plural': 'Navbars',
            },
        ),
        migrations.CreateModel(
            name='Strongest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('logo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'The strongest',
                'verbose_name_plural': 'The strongest',
            },
        ),
        migrations.CreateModel(
            name='TimeMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_meeting_1', models.DateField(blank=True, null=True)),
                ('time_meeting_1', models.TimeField(blank=True, null=True)),
                ('date_meeting_2', models.DateField(blank=True, null=True)),
                ('time_meeting_2', models.TimeField(blank=True, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetting.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+', max_length=15)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetting.meeting')),
            ],
        ),
    ]
