# Generated by Django 4.1.6 on 2023-04-16 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetting', '0002_alter_strongest_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='video',
            field=models.FileField(help_text='Upload video', upload_to='video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
